# Edit this file to set the AWS-Comprehend module settings programmatically instead of using the GUI
# This is regular YAML syntax. See http://docs.ansible.com/ansible/YAMLSyntax.html
# You can override these settings with ENV variables. They are commented below.

accessKeyId: "" # ENV AWD_ACCESS_KEY_ID
secretAccessKey: "" # ENV AWS_SECRET_ACCESS_KEY
region : "" # ENV AWS_REGION
apiVersion: "" # ENV AWS_API_VERSION